In [107]:
import pandas as pd
import matplotlib as mp
import seaborn as sb
import numpy as np
import scipy as sp
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [108]:
df = pd.read_csv(r'C:\Users\archi\Downloads\archive (2) (1)\chat_dataset.csv')

In [109]:
df.head()

                              message sentiment
0          I really enjoyed the movie  positive
1               The food was terrible  negative
2  I'm not sure how I feel about this   neutral
3           The service was excellent  positive
4              I had a bad experience  negative

In [110]:
df.tail()

                                               message sentiment
579  I have to cancel my vacation plans because I c...  negative
580  My computer crashed and I lost all my importan...  negative
581  I got into a car accident and my car is totale...  negative
582  I have a cold and can't stop coughing. it's re...  negative
583  I just found out my ex is dating someone new. ...  negative

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 584 entries, 0 to 583
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   message    584 non-null    object
 1   sentiment  584 non-null    object
dtypes: object(2)
memory usage: 9.3+ KB

In [112]:
df.isnull().sum()

message      0
sentiment    0
dtype: int64

In [113]:
df.describe()

                          message sentiment
count                         584       584
unique                        546         3
top     I have no opinion on this   neutral
freq                            5       259

In [114]:
lbl = LabelEncoder()

In [115]:
labels=lbl.fit_transform(df.sentiment)

In [116]:
df['target']=labels

In [117]:
y=labels

In [118]:
df['target'].value_counts()

target
1    259
2    178
0    147
Name: count, dtype: int64

In [119]:
df['sentiment'].value_counts()

sentiment
neutral     259
positive    178
negative    147
Name: count, dtype: int64

In [120]:
vector = CountVectorizer()

In [121]:
vector

CountVectorizer()

In [122]:
corpus = df.message

In [123]:
print(corpus)

0                             I really enjoyed the movie
1                                  The food was terrible
2                     I'm not sure how I feel about this
3                              The service was excellent
4                                 I had a bad experience
                             ...
579    I have to cancel my vacation plans because I c...
580    My computer crashed and I lost all my importan...
581    I got into a car accident and my car is totale...
582    I have a cold and can't stop coughing. it's re...
583    I just found out my ex is dating someone new. ...
Name: message, Length: 584, dtype: object

In [124]:
X= vector.fit_transform(corpus)
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3495 stored elements and shape (584, 684)>

In [125]:
x_train,x_test,y_train,y_test= train_test_split(X,y,test_size=0.2)

In [126]:
x_train.shape

(467, 684)

In [127]:
y_train.shape

(467,)

In [128]:
y_test.shape

(117,)

In [129]:
x_train.toarray()[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [130]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [131]:
msg=['This software is bad','The quality of the product is so good ','I dont really care about this']
msgtr= vector.transform(msg)
model.predict(msgtr)

array([1, 2, 1])

In [134]:
model.score(x_test,y_test)

0.811965811965812